### ISSUE TITLE
Creating a Branch Generates Several Banners

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-version-control#139]
To recreate:

1. Create a new branch `test_branch_bravo` (notice a lot of headers)

Notice a lot of headers (3 of them), and as you navigate through the pages of Nautobot, if you do not dismiss the notification this will continue to increment.

**Comment by mzbroch** [comment]
An example of the issue :

![image](https://user-images.githubusercontent.com/16935122/145403827-a9a212df-b12a-4b5d-b33a-8d0346194eb2.png)
