### ISSUE TITLE
Dropdown selectors don't work on non-main branches when creating an object in Nautobot 1.2b

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#151]
On a non-main branch, when running Version Control with Nautobot 1.2b, the dropdown selectors can't load their options when creating a new object.  The user sees a message in the dropdown that says `The results could not be loaded`.

To replicate: 
* Create a new branch 
* When the new, non-main branch is active, attempt to create a new device
* Select (for example) select a value for Device Type
* After, attempt to select a value for Device Role (here you will see a message in the dropdown that says `The results could not be loaded`)

This problem only appears in the Nautobot 1.2b running Version Control when a non-main branch is active.  

This problem does **not** happen on the Version Control main branch running 1.2b or on a non-Version Control instance of Nautobot running 1.2b.

The first time the user accesses any dropdown menu, the selection options appear:

![image](https://user-images.githubusercontent.com/13647153/144288952-9cc82abd-3661-482e-ac72-03edb1103a8b.png)

But after that, any other dropdowns cannot display their options:

![image](https://user-images.githubusercontent.com/13647153/144289362-272983ba-cadb-4ecb-b848-a4a27c1bc09b.png)

Running Nautobot v1.2.0b1:
![image](https://user-images.githubusercontent.com/13647153/144289575-0dd82d93-134c-4a0d-8ca9-4dd0344e7d24.png)

**Comment by glennmatthews** [comment]
The response being returned on the second and subsequent menu-driven API calls is a 500 error with HTML content including:

```
<class 'dolt.utils.DoltError'>

Error writing model Session
                        on branch "test-branch":
                        non-versioned models must be written on branch
                        "main".
```

**Comment by glennmatthews** [comment]
As such this may share the same root cause as #152?

**Comment by glennmatthews** [comment]
Perhaps also #132?

**Comment by glennmatthews** [comment]
I can reproduce this on the demo site, but thus far I do *not* see it in a local development environment:

![image](https://user-images.githubusercontent.com/5603551/145117062-f05983bf-d150-4eed-b2e1-9929c19abc62.png)

**Comment by tim-fiola** [comment]
fixed in https://github.com/networktocode-llc/gizmo-dolt-nautobot/pull/9
