### ISSUE TITLE
Commits tab shows 'nautobot' as committer, even when a different user makes the commit

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#154]
When a user that does not have a username of _nautobot_  makes a change, the **_Version Control --> Commits_** entries always show the committer as _nautobot_

One of the advantages that the Commits view brings, especially to the main branch, is that it offers an auditable history of changes to the production data: who made what change and when.  However, if the **Committer** always shows as _nautobot_, this makes the Commits history much less valuable

In this example below, as user tim, I made the most recent (top) change in the list, but the **Committer** shows as _nautobot_
![image](https://user-images.githubusercontent.com/13647153/144939310-ee306553-0a2e-4f2b-b0b2-bc2d06d6554c.png)

To replicate: 
* In any branch, make a change
* Go to Version Control --> Commits
* Note the **Committer** will show up as _nautobot_

**Comment by glennmatthews** [comment]
Looks like this is due to logic in `author_from_user` - it defaults to `nautobot <nautobot@ntc.com>` if the provided user doesn't have an email address on record.
