### ISSUE TITLE
improve merge conflict UI 

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#26]
example from @glennmatthews 
![image](https://user-images.githubusercontent.com/6332586/130131063-8aff3c55-09bb-44a8-800f-a0e15307efd5.png)

Need to decide if we would shade the conflicting values' backgrounds different colors for more contrast? AND/OR slightly more padding between the lines in a single row...

**Comment by jedelman8** [comment]
let's add a screenshot of what it is for now.

**Comment by andrew-wm-arthur** [comment]
![image](https://user-images.githubusercontent.com/8837413/132901789-d5ee7673-6e23-4343-a19a-dcb509dcdad0.png)
