### ISSUE TITLE
"Ahead/Behind" computed column in Branch list view

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#27]
From the branch list view, the user should be able to see the number of commits "ahead" and "behind" that each branch is from the primary branch. This mirrors the same functionality on Github.

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-08 at 2 26 54 PM](https://user-images.githubusercontent.com/7027863/132587921-565edcf4-e5c1-45a6-8051-9ffd0b66a674.png)
