### ISSUE TITLE
Show author and source branch in the branch list view

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#28]

**Comment by andrew-wm-arthur** [comment]
Add "starting branch" to list view

![image](https://user-images.githubusercontent.com/8837413/132893474-dbddb014-dc80-4422-9b4f-0d2b8b58e919.png)

**Comment by andrew-wm-arthur** [comment]
remove "Latest committer email" column

**Comment by VinaiRachakonda** [comment]
Do we prefer "source_branch" or "starting_branch"

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-10 at 1 10 46 PM](https://user-images.githubusercontent.com/7027863/132911946-41b4f5a4-bca1-4bc7-84ab-24e7b6873a1e.png)
