### ISSUE TITLE
Commit messages with many changes should be summarized

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#29]
The "`short_message()` computed field for the `Commit` model currently shortens long commit messages to only show the first change in the message. This should be altered to also summarize the number of total changes in the commit

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132587769-b332f64a-18f2-4ff5-af92-40afa26465cc.png)
