### ISSUE TITLE
Add 'Branch Name' column to Branch Commits view

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#32]
The `Commits in <branch name>` page should have a column that contains the name of the branch that each commit was a part of.  That is not evident from the current data displayed.

![image](https://user-images.githubusercontent.com/13647153/130700120-9700acac-23b9-4aa0-89c4-51c1cc5a2109.png)

**Comment by tim-fiola** [comment]
The name of the PR should also have a column to relieve the user from having to parse that info (if possible) from the commit messages

**Comment by jedelman8** [comment]
we're going to add a blue label around the branch name and the word "branch" after it, so it'll be "Commits in main branch" where "main" will be a blue label.

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-09 at 11 51 58 AM](https://user-images.githubusercontent.com/7027863/132746038-541e0a14-b47d-4773-9e23-aa3dc0a32ecd.png)

Seeing some slight problems here with how titles are rendered

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-10 at 9 56 48 AM](https://user-images.githubusercontent.com/7027863/132890072-6b519298-77e5-453d-871b-d721afc8a8d0.png)

**Comment by andrew-wm-arthur** [comment]
Overload "title" block in Django template to fix html title issue

**Comment by VinaiRachakonda** [comment]
Reopening to fix title problem. Will address today

**Comment by VinaiRachakonda** [comment]
This doesn't seem possible with the templating setup. Would prefer to punt or close

**Comment by andrew-wm-arthur** [comment]
We'll address the tab title issue in a separate issue. The primary issue of changing the title of the commit log view has been addressed
