### ISSUE TITLE
Pull Request Screen 'State' and 'Status' Appear To Be Same Thing

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#33]
The Pull Requests page has a column header of `Status`; the Search box to the right has a `State` field.  These appear to reference the same thing

![image](https://user-images.githubusercontent.com/13647153/130700791-d757d54b-dc23-4844-a362-a35dd33083ef.png)

**Comment by jedelman8** [comment]
Going to change State to Status and make it a mulit-select.
