### ISSUE TITLE
New PRs from a branch should populate that branch as 'Source Branch'

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#34]
When user is working on a branch that has diffs, the 'Add a new pull request' screen should default to using that branch as the 'Source Branch'.

In the example below, I'm on the `atl-augment` branch.  When I create a PR, the Source Branch should auto-populate with `atl-augment`.

![image](https://user-images.githubusercontent.com/13647153/130850150-445803a5-9980-4ff0-ba72-7828d287f968.png)

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-10 at 1 37 36 PM](https://user-images.githubusercontent.com/7027863/132914869-fd21cba0-9640-4265-9611-2cff008c5d59.png)

I have this as part of a large pr
