### ISSUE TITLE
Device's 'Status' change shows some kind of hash in Diffs view

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#35]
Reviewing Diffs for a recent PR.  One of the changes was changing a Device's status from `Active` to `Decommissioning`.

On the Pull Requests screen, the Status change shows some kind of hash or UUID.  I'd expect to see the text value of the status: Before status as `Active` and the After status as `Decommissioning`. 

![image](https://user-images.githubusercontent.com/13647153/130850905-0b8dbf9d-ff8f-48fb-8501-4f8be7a6ec50.png)

**Comment by andrew-wm-arthur** [comment]
After discussion with Jason, the deliverable is a human-readable string for each of the before/after fields

**Comment by andrew-wm-arthur** [comment]
New Diff Detail View
![image](https://user-images.githubusercontent.com/8837413/131940315-b4a92cb0-e489-47b9-9358-d42a4b8733f3.png)

**Comment by andrew-wm-arthur** [comment]
![image](https://user-images.githubusercontent.com/8837413/132070663-f66a1b14-e8d9-47b3-9697-a01c545e4374.png)

**Comment by andrew-wm-arthur** [comment]
@jedelman8 are you good with this one?
