### ISSUE TITLE
On main page for a branch, have a button available to checkout the branch

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#36]
The main page for a given branch should have the option to checkout the branch (if checkout is still possible)

![image](https://user-images.githubusercontent.com/13647153/131003170-9f86ee73-29a2-4774-bf73-3370967526e3.png)

**Comment by jedelman8** [comment]
Makes sense. Use "Active" button.

**Comment by andrew-wm-arthur** [comment]
![image](https://user-images.githubusercontent.com/8837413/132891986-2f29a677-03c7-42ff-92dc-de52793ee2ce.png)

**Comment by andrew-wm-arthur** [comment]
Change verbage from "checkout" to "activate"

**Comment by VinaiRachakonda** [comment]
<img width="1777" alt="Screen Shot 2021-09-14 at 7 27 53 AM" src="https://user-images.githubusercontent.com/7027863/133276458-0de3a50b-5c9a-484f-9758-465cd5b8804f.png">

Verbage is now activate

**Comment by VinaiRachakonda** [comment]
@andrew-wm-arthur Can we close?

**Comment by andrew-wm-arthur** [comment]
@jedelman8 this one is ready to close
