### ISSUE TITLE
Squash Merge for Pull Requests

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#37]
Add support for optionally squashing commits while [merging](https://docs.dolthub.com/interfaces/cli#dolt-merge) pull requests

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-08 at 2 24 52 PM](https://user-images.githubusercontent.com/7027863/132587692-cf5f4502-da71-4c07-95be-b490ae1fc4a9.png)
