### ISSUE TITLE
Share Button to create versioned links

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#42]
When using Nautobot with the Dolt plugin, Branch state information is stored in the session cookie. This state is not encoded in the URL and sharing links will therefor lack the necessary branch context. 

In order to share "versioned links" users will use a "share" button that will created a version of the current URL with the branch-state encoded

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132889632-75ba1d13-ee4b-4e5e-a61e-cf87022df2da.png)
