### ISSUE TITLE
add column in branch table to show "active" status

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#43]
keep green "Active" but make label and should be in column 2

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132889726-8739886f-40c2-47a4-99ef-ca5e315f5c56.png)

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132901657-848570f0-b303-45ec-ae2a-a8f0531249d5.png)
