### ISSUE TITLE
add "Catch up" button to branch table redirecting to PR page

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#45]

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132889711-c5403d5c-8e5a-422d-ada4-c246aa9c738f.png)

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132901620-6d934117-f39c-47aa-9dae-662b16cbfd9c.png)
