### ISSUE TITLE
replace "checkout" with "Activate" button in branch table

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#46]

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132889700-5eab60dc-14d9-41fb-b149-2a7881303b07.png)

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/132901491-0511423e-f254-4faf-83a0-5b95fc5fb6ad.png)
