### ISSUE TITLE
Add API endpoints

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#47]
- [ ] PRs
- [ ] PR Comments
- [ ] Branches
- [ ] Commits (includes revert)

**Comment by andrew-wm-arthur** [comment]
![image](https://user-images.githubusercontent.com/8837413/132892851-a4285c68-91f5-491a-87f6-0f9741aa5b1f.png)

**Comment by VinaiRachakonda** [comment]
Reopening due to confusion on pull request comments vs just pull request reviews
