### ISSUE TITLE
question: should we support deleting PRs?

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#48]

**Comment by VinaiRachakonda** [comment]
![image](https://user-images.githubusercontent.com/7027863/133278146-042d49b1-e157-4b22-9ded-e4a9afc99e83.png)

**Comment by VinaiRachakonda** [comment]
Block branch deletes when un deleted pr exists

**Comment by VinaiRachakonda** [comment]
Seemed to be a problem with how global state was being written
