### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#54]

**Comment by andrew-wm-arthur** [comment]
# Comment Docs
# User Documentation

- [ ] Common Workflows
- [ ] Restrictions to versioning

# Developer Documentation

- [ ] Dolt overview
- [ ] Versioning Model
- [ ] Global state model
- [ ] Restrictions to model

# Plugin Development Documentation

- [ ] Registering Versioned Models

**Comment by tim-fiola** [comment]
Comment Documentation
---

User Documentation ( to own)
---
  - [ ] Concepts
    - [ ] Branches
      - [ ] Main (default name)
      - [ ] Others
    - [ ] Commits
      - [ ] What is a commit?
      - [ ] How do commits happen?
        - [ ] When users modify anything in a branch
    - [ ] Pull Requests
    - [ ] Merges
  - [ ] Common Workflows
    - [ ] Proposing a Change to the Data - Creating a branch, making changes, reviewing changes
    - [ ] The Pull Request (PR) process
    - [ ] Individual Commit Reversions
    - [ ] Mass Reversions
      - [ ] Roll back an entire merge
      - [ ] Roll back an entire
  - [ ] Restrictions to versioning

Developer Documentation (who writes this?)
---
  - [ ] Dolt overview
  - [ ] Versioning Model
  - [ ] Global state model
  - [ ] Restrictions to model
- [ ] Plugin Development Documentation
  - [ ] Registering Versioned Models
- [ ] RESTful API Queries Against Branches (@tim-fiola can write this)
