### ISSUE TITLE
change name of drop down and API slug

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-version-control#68]
Let's change the name in the navbar from "Dolt" to "Version Control" and `dolt` within API URLs to `version-control`.

**Comment by dgarros** [comment]
We could also rename the header for the API to `branch` instead of `dolt-branch`

**Comment by jedelman8** [comment]
I'm good either way on this since it is technically still a "dolt" branch.  Anyone else have an opinion?

**Comment by jedelman8** [comment]
@andrew-wm-arthur re-opening as I don't see this in the "demo" environment.

**Comment by andrew-wm-arthur** [comment]
@jedelman8 good catch, I addressed this in https://github.com/nautobot/nautobot-plugin-version-control/commit/abd12aae0f1c4a684ce89c7eaeaca81bd1d37e68 and updated the demo instance
