### ISSUE TITLE
Branch Delete Message is incomplete

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#95]
![image](https://user-images.githubusercontent.com/8837413/133829093-a5518464-6c64-412a-b2f7-b5247eac77f1.png)

**Comment by andrew-wm-arthur** [comment]
Also Missing error message for branch deletions blocked by branch protection rules

**Comment by VinaiRachakonda** [comment]
![Screen Shot 2021-09-21 at 12 12 57 PM](https://user-images.githubusercontent.com/7027863/134233210-4da04553-642a-4185-ab42-95bba53924b7.png)
