### ISSUE TITLE
Filter Form Fields for Branch List view 

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#97]
ability to filter by "created by", "last committer", "source branch"

**Comment by andrew-wm-arthur** [comment]
This is the current state of the branches filter view:
![image](https://user-images.githubusercontent.com/8837413/134432055-5381a759-ea32-4f22-917e-ed707223d8ac.png)

Filtering on "created by" or "source branch" is somewhat incompatible with the current plugin models. 

The data in this list view comes from the Branch and BranchMeta models. The Branch model is an "unmanaged" ORM wrapper around the `dolt_branches` system table. The consequence is that its model fields are determined by the database, not by the plugin code. In order to store additional information  "created by" and "source branch", each Branch object has an associated BranchMeta object. However, this relationship is not formalized with a Foreign Key due to limitations with the `dolt_branches` table.

**Comment by glennmatthews** [comment]
Are the `created_by` and `source_branch` columns sortable (by clicking on the column header to resort the table)? If not, these columns should be declared in code as `orderable=False` so that the column header doesn't display as clickable.
